// src/config/permissions.ts
export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_CLAIMS: "MANAGE_CLAIMS",
  MANAGE_CUSTOMERS: "MANAGE_CUSTOMERS",
  MANAGE_DOCUMENTS: "MANAGE_DOCUMENTS",
  MANAGE_SIGNATURES: "MANAGE_SIGNATURES",
  MANAGE_INTEGRATIONS: "MANAGE_INTEGRATIONS",
  MANAGE_COMPANIES: "MANAGE_COMPANIES",
  MANAGE_CONFIG: "MANAGE_CONFIG",
  VIEW_REPORTS: "VIEW_REPORTS",
} as const;

export type PermissionType = keyof typeof PERMISSIONS;
